---
accelerated: True
height: 1024
width: 1024
center_real: -0.7435
center_imaginary: 0.1314
world_width: 0.002
max_iterations: 512
color_scheme: 3
builtin_colormap: True
colormap: twilight
mixed_raster: True
fast_quadtree: True
...
